language: go
go:
- 1.16.x
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - xorg-dev
    - libasound2-dev
services:
- xvfb
before_install:
- go get -v golang.org/x/lint/golint
- export DISPLAY=:99.0
jobs:
  include:
  - stage: lint and test
    os: linux
    script:
    - golint ./...
    - go vet ./...
    - go test -v -cover ./...
  - stage: build for windows and linux
    script:
    - mkdir release
    - CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o release/kuronan-dash_windows_amd64.exe
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o release/kuronan-dash_linux_amd64
  - stage: build for macOS
    os: osx
    osx_image: xcode11.3
    script:
    - mkdir release
    - CGO_ENABLED=1 go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o release/kuronan-dash_macOS_amd64
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: e0qT1neTUtV/A5QiDec5spZ2u5buLPai1mya+RndLZIPBpAAyubHlJjfmUIttvemxgBbqFrqcnDeBdm5ctqIQA4EXh63e3eZOYt/uEzffUwYET4IWoC//G4imqQ3vuA9d1Qt8HcT0Bj4pxgql5ExV/MqhMYIKAjXYy3lb8AHEMXEduGi2yoIZC2Su89J99EbXpHK7rsZOpfixVUCwPW8jtyu3Ow7CpAjJDhQOsyKei49HTAj4sdl4yWrQM7fbO9ig0EFnCGTIwH2Yy3x9B1V1U7cm20wC5A3UCOC4fHBqzOBuF85v+Cc9ZURI8vMXenSzrdjSNIu1yVSdZaZk5V5qHc+es3pLbdXP0ajBeL3cz+9LtE+nkkVNPxnwnmKhrAcV4UxE7xtNLmkm/S45JrANnpRegYrSgLo2RR/8cneaU8BC3U66SRuyzjOVnGZQpL5eNjvOYOmvQPmDKvvRVBiNCuCP/vCXPpEEy9WoLuy7D0uELP6e9YF9cNkItxyVXMnRvJknq4qv74v8nghLYi41D5mC+Xl9o+EqyTq5vB6WvnobNY63eNZRL3x53dj3kAo9KkmzCmFovyHZurxuldEJBPOvZKfrvI3M/5NnWenneo7nOLp8CB4ERH3sFLu7cfGNzxxpNhVTrknY1LsrLKT6PsoqsvgVxqrw8rDIIA4Zhs=
  file_glob: true
  file: release/*
  on:
    tags: true
    repo: kemokemo/kuronan-dash
