language: go
go:
- 1.16.x
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - xorg-dev
    - libasound2-dev
services:
- xvfb
before_install:
- go get -v golang.org/x/lint/golint
- export DISPLAY=:99.0
jobs:
  include:
  - stage: lint and test
    os: linux
    script:
    - golint ./...
    - go vet ./...
    - go test -v -cover ./...
  - stage: build for windows and linux
    script:
    - mkdir release
    - CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o release/kuronan-dash_windows_amd64.exe
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o release/kuronan-dash_linux_amd64
  - stage: build for macOS
    os: osx
    osx_image: xcode11.3
    script:
    - mkdir release
    - CGO_ENABLED=1 go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o release/kuronan-dash_macOS_amd64
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CwyIqE/EzzHwJ3mqqsWi6BKiM0qhxajIILWzktnLOcRhh/pPvyMaXYTk75IZkl/JLCC15i/MyXeEd0seLwVzb7P5qrbWapduPn2q8ZipRStg1Dm0y/zHWmA/RO03R4icCYcEQVRxoNma4SU/oZ2HspavoIKC8Wk3R6nurxv49+zp5UjCxLG77cXGbzV/GpgC67Vlt5iDyyL1SFYTveyU42MiQ4yT6eitJJYqAKgg6hAop/IEnV7/VW/GXNb4YcsfdyYej4MFbF4okNHTXMUD3y32zFGeibJ+WTZ1CJoR4Fhz3nwrLYwu2yBZQRB3QS8WVIMjidHrRWco+VSWgjDg/H+BE9mPpeqFcp5yiy5h0F6l4BbsP3Ty8g7ZivyYozuBE5srx8JbHxjepZUBQJjB8/Ptv3OHBR/6Ju+4A/nfO9DNGmdHPYf6aJ0J9JzPpWL45Xw4hMvR3RG+HAqnbdt6SoCBcneyOTXNN6dTl9+HbOnfFhdwFMaouIVXEWhm1TLrsKk7TNLBYvfh39NjYjjIq+H+1iBMcyDE8ClDhtmwwcxBrk5sUux9wAp3f5Po07GBJppnjNmsRYTGGAM7JW+RU0m75PFeNCMia8rubpa2iBaPixVObRTh4+5Q/s27u6goPIK1OSivAU//4uvyYDBE8ubOAdu8Qw4JuYvGzAgidew=
  file_glob: true
  file: release/*
  on:
    tags: true
    repo: kemokemo/kuronan-dash
